// <auto-generated />
using System;
using EventManagement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventManagement.Migrations
{
    [DbContext(typeof(EventManagementDbContext))]
    [Migration("20260326071319_InitialRebuild")]
    partial class InitialRebuild
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventManagement.Models.AreaMaster", b =>
                {
                    b.Property<int>("Area_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Area_Id"));

                    b.Property<string>("Area_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Area_Status")
                        .HasColumnType("bit");

                    b.Property<int>("City_Id_fk")
                        .HasColumnType("int");

                    b.HasKey("Area_Id");

                    b.HasIndex("City_Id_fk");

                    b.ToTable("Area_Master");
                });

            modelBuilder.Entity("EventManagement.Models.BookingCartDetail", b =>
                {
                    b.Property<int>("Booking_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Booking_Id"));

                    b.Property<decimal>("Ammount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("Booking_Reference")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Booking_Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("datetime2");

                    b.Property<int>("Custom_Id_fk")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Event_Manager_Approved")
                        .HasColumnType("bit");

                    b.Property<int?>("Event_Manager_Login_Id_fk")
                        .HasColumnType("int");

                    b.Property<int>("Event_Package_Id_fk")
                        .HasColumnType("int");

                    b.Property<int>("Guest_Count")
                        .HasColumnType("int");

                    b.Property<string>("Payment_Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Booking_Id");

                    b.HasIndex("Custom_Id_fk");

                    b.HasIndex("Event_Manager_Login_Id_fk");

                    b.HasIndex("Event_Package_Id_fk");

                    b.ToTable("Booking_Cart_Detail");
                });

            modelBuilder.Entity("EventManagement.Models.BookingServiceDetail", b =>
                {
                    b.Property<int>("Booking_Service_Detail_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Booking_Service_Detail_Id"));

                    b.Property<int>("Booking_Id_fk")
                        .HasColumnType("int");

                    b.Property<string>("Confirmation_Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Confirmed_On")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("Provider_Comment")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Service_Catalog_Item_Id_fk")
                        .HasColumnType("int");

                    b.Property<string>("Service_Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Booking_Service_Detail_Id");

                    b.HasIndex("Booking_Id_fk");

                    b.HasIndex("Service_Catalog_Item_Id_fk");

                    b.ToTable("Booking_Service_Detail");
                });

            modelBuilder.Entity("EventManagement.Models.CityMaster", b =>
                {
                    b.Property<int>("City_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("City_Id"));

                    b.Property<string>("City_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("City_Status")
                        .HasColumnType("bit");

                    b.Property<int>("State_Id_fk")
                        .HasColumnType("int");

                    b.HasKey("City_Id");

                    b.HasIndex("State_Id_fk");

                    b.ToTable("City_Master");
                });

            modelBuilder.Entity("EventManagement.Models.EventStatusMaster", b =>
                {
                    b.Property<int>("Event_Status_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Event_Status_Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Event_Booking_Cart_fk")
                        .HasColumnType("int");

                    b.Property<string>("Event_Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Event_Type_Id_fk")
                        .HasColumnType("int");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Service_Person_Id_fk")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Event_Status_Id");

                    b.HasIndex("Event_Booking_Cart_fk");

                    b.HasIndex("Service_Person_Id_fk");

                    b.ToTable("Event_Status_Master");
                });

            modelBuilder.Entity("EventManagement.Models.EventTypeMaster", b =>
                {
                    b.Property<int>("Event_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Event_Id"));

                    b.Property<string>("Event_Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Event_Type_Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Event_Id");

                    b.ToTable("Event_Type_Master");
                });

            modelBuilder.Entity("EventManagement.Models.FeedBackDetail", b =>
                {
                    b.Property<int>("FeedBack_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedBack_Id"));

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FeedBack")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FeedBack_Status")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("FeedBack_Id");

                    b.ToTable("FeedBack_Detail");
                });

            modelBuilder.Entity("EventManagement.Models.InquiryDetail", b =>
                {
                    b.Property<int>("Inquiry_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Inquiry_Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("Inquiry_Status")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("Response_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Inquiry_Id");

                    b.ToTable("Inquiry_Detail");
                });

            modelBuilder.Entity("EventManagement.Models.LoginDetail", b =>
                {
                    b.Property<int>("Login_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Login_Id"));

                    b.Property<bool>("Is_Active")
                        .HasColumnType("bit");

                    b.Property<string>("Last_Notification")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("Must_Change_Password")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Roll_Id_fk")
                        .HasColumnType("int");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Login_Id");

                    b.HasIndex("Roll_Id_fk");

                    b.ToTable("Login_Detail");
                });

            modelBuilder.Entity("EventManagement.Models.PaymentDetail", b =>
                {
                    b.Property<int>("Payment_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Payment_Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("Booking_Id_fk")
                        .HasColumnType("int");

                    b.Property<DateTime>("Paid_On")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payment_Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Payment_Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Transaction_Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Payment_Id");

                    b.HasIndex("Booking_Id_fk");

                    b.ToTable("Payment_Detail");
                });

            modelBuilder.Entity("EventManagement.Models.RollDetail", b =>
                {
                    b.Property<int>("Roll_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Roll_Id"));

                    b.Property<string>("Roll_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Roll_Id");

                    b.ToTable("Roll_Detail");
                });

            modelBuilder.Entity("EventManagement.Models.ServiceCatalogItem", b =>
                {
                    b.Property<int>("Service_Catalog_Item_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Service_Catalog_Item_Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Event_Type_Id_fk")
                        .HasColumnType("int");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("bit");

                    b.Property<string>("Photo_Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("Service_Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Service_Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("Service_Provider_Id_fk")
                        .HasColumnType("int");

                    b.HasKey("Service_Catalog_Item_Id");

                    b.HasIndex("Event_Type_Id_fk");

                    b.HasIndex("Service_Provider_Id_fk");

                    b.ToTable("Service_Catalog_Item");
                });

            modelBuilder.Entity("EventManagement.Models.ServiceProvider", b =>
                {
                    b.Property<int>("Service_Provider_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Service_Provider_Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Approval_Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Email_Id")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("Is_Blocked")
                        .HasColumnType("bit");

                    b.Property<int>("Login_Id_fk")
                        .HasColumnType("int");

                    b.Property<string>("Profile_Image_Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Rejection_Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Service_Provider_Area_Id_fk")
                        .HasColumnType("int");

                    b.Property<string>("Service_Provider_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Service_Provider_Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Service_Provider_Id");

                    b.HasIndex("Login_Id_fk");

                    b.HasIndex("Service_Provider_Area_Id_fk");

                    b.ToTable("Service_Provider");
                });

            modelBuilder.Entity("EventManagement.Models.StateMaster", b =>
                {
                    b.Property<int>("State_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("State_Id"));

                    b.Property<string>("State_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("State_Status")
                        .HasColumnType("bit");

                    b.HasKey("State_Id");

                    b.ToTable("State_Master");
                });

            modelBuilder.Entity("EventManagement.Models.UserRegistrationDetail", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Area_Id_fk")
                        .HasColumnType("int");

                    b.Property<string>("Contact_No")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email_Id")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Login_Id_fk")
                        .HasColumnType("int");

                    b.HasKey("User_Id");

                    b.HasIndex("Area_Id_fk");

                    b.HasIndex("Login_Id_fk");

                    b.ToTable("User_Registration_Detail");
                });

            modelBuilder.Entity("EventManagement.Models.AreaMaster", b =>
                {
                    b.HasOne("EventManagement.Models.CityMaster", "City")
                        .WithMany("Areas")
                        .HasForeignKey("City_Id_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("EventManagement.Models.BookingCartDetail", b =>
                {
                    b.HasOne("EventManagement.Models.UserRegistrationDetail", "Customer")
                        .WithMany()
                        .HasForeignKey("Custom_Id_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventManagement.Models.LoginDetail", "EventManagerLogin")
                        .WithMany()
                        .HasForeignKey("Event_Manager_Login_Id_fk");

                    b.HasOne("EventManagement.Models.EventTypeMaster", "EventType")
                        .WithMany()
                        .HasForeignKey("Event_Package_Id_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("EventManagerLogin");

                    b.Navigation("EventType");
                });

            modelBuilder.Entity("EventManagement.Models.BookingServiceDetail", b =>
                {
                    b.HasOne("EventManagement.Models.BookingCartDetail", "Booking")
                        .WithMany("Services")
                        .HasForeignKey("Booking_Id_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventManagement.Models.ServiceCatalogItem", "ServiceCatalogItem")
                        .WithMany("BookingServices")
                        .HasForeignKey("Service_Catalog_Item_Id_fk")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("ServiceCatalogItem");
                });

            modelBuilder.Entity("EventManagement.Models.CityMaster", b =>
                {
                    b.HasOne("EventManagement.Models.StateMaster", "State")
                        .WithMany("Cities")
                        .HasForeignKey("State_Id_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("EventManagement.Models.EventStatusMaster", b =>
                {
                    b.HasOne("EventManagement.Models.BookingCartDetail", "Booking")
                        .WithMany("StatusUpdates")
                        .HasForeignKey("Event_Booking_Cart_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventManagement.Models.LoginDetail", "ServicePersonLogin")
                        .WithMany()
                        .HasForeignKey("Service_Person_Id_fk")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("ServicePersonLogin");
                });

            modelBuilder.Entity("EventManagement.Models.LoginDetail", b =>
                {
                    b.HasOne("EventManagement.Models.RollDetail", "Roll")
                        .WithMany()
                        .HasForeignKey("Roll_Id_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roll");
                });

            modelBuilder.Entity("EventManagement.Models.PaymentDetail", b =>
                {
                    b.HasOne("EventManagement.Models.BookingCartDetail", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("Booking_Id_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("EventManagement.Models.ServiceCatalogItem", b =>
                {
                    b.HasOne("EventManagement.Models.EventTypeMaster", "EventType")
                        .WithMany("Services")
                        .HasForeignKey("Event_Type_Id_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventManagement.Models.ServiceProvider", "ServiceProvider")
                        .WithMany("Services")
                        .HasForeignKey("Service_Provider_Id_fk")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EventType");

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("EventManagement.Models.ServiceProvider", b =>
                {
                    b.HasOne("EventManagement.Models.LoginDetail", "Login")
                        .WithMany()
                        .HasForeignKey("Login_Id_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventManagement.Models.AreaMaster", "Area")
                        .WithMany()
                        .HasForeignKey("Service_Provider_Area_Id_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Login");
                });

            modelBuilder.Entity("EventManagement.Models.UserRegistrationDetail", b =>
                {
                    b.HasOne("EventManagement.Models.AreaMaster", "Area")
                        .WithMany("Users")
                        .HasForeignKey("Area_Id_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventManagement.Models.LoginDetail", "Login")
                        .WithMany()
                        .HasForeignKey("Login_Id_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Login");
                });

            modelBuilder.Entity("EventManagement.Models.AreaMaster", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EventManagement.Models.BookingCartDetail", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Services");

                    b.Navigation("StatusUpdates");
                });

            modelBuilder.Entity("EventManagement.Models.CityMaster", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("EventManagement.Models.EventTypeMaster", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("EventManagement.Models.ServiceCatalogItem", b =>
                {
                    b.Navigation("BookingServices");
                });

            modelBuilder.Entity("EventManagement.Models.ServiceProvider", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("EventManagement.Models.StateMaster", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
